---
- name: Ensure snippets folder exists
  ansible.builtin.file:
    path: "{{ pve_media_upload_snippets_folder_path }}"
    state: directory
    mode: '0755'
  when: pve_media_upload_snippets | length >0

- name: Template the snippets
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ pve_media_upload_snippets_folder_path }}/{{ item.dest }}"
    mode: '0755'
  loop: "{{ pve_media_upload_snippets | default([]) }}"
...
